### ISSUE TITLE
Not working on my board.

### ISSUE THREAD

**Issue by won0-kim** [stacksmashing/airtag-glitcher#2]
Hi

I bought a pico debug n dump v1.1. 
However, it seems that the firmware doesn't work on my board.
At first, the screen doesn't show anything and LED also won't turn on. I'm not sure this firmware has led blink code but when I uploaded pico's example code, it worked successfully. 
Furthermore, my jupyter notebook stops at `10/21000 [00:01<47:30, 7.36it/s]` and it doesn't go more. 

did I  do something wrong?

**Comment by ForkYeahh** [comment]
@won0-kim I'm having the same issue where my juptyer notebook stops at around `28/21000 [00:01<47:30, 7.36it/s]` for me. At first I thought my pico froze at that point but after checking the wires with a logic analyzer it shows that everything does seem te be working even if it doesn't look like it in the jupyter notebook.

Did you manage to find a solution to this problem?

**Comment by nezza** [comment]
I have a more up-to-date Nrf Glitcher, I'll try to upload it soon-ish.

**Comment by ForkYeahh** [comment]
@nezza Cool, will you update this repo or upload it elsewhere? In any case could you let us know when you've uploaded the new version? Would be much appreciated if you could!

**Comment by ForkYeahh** [comment]
Any update on this @nezza ? When I'm glitching the pulse or delay sometimes gets corrupted and becomes a very high integer which causes the glitch to crash. This happens very randomly and I'm not sure why this is happening. When I hook up a logic analyzer to my setup and check when the glitching happens and the power cycling, that all seems to be working perfectly until the data becomes corrupted for some reason. 

I'm not using a pico debug n dump by the way but my own setup based on https://github.com/ensingerphilipp/airtag-glitch-dump-improved

**Comment by ForkYeahh** [comment]
Nvm fixed the issue by downgrading the pico sdk (from 1.5.1 to 1.2.0)

**Comment by nezza** [comment]
It looks like current pico-sdk sometimes has issues with fread (or I'm using it wrong..) - replacing it with getc seems to work stable
