### ISSUE TITLE
Glitch pin not shorting to ground

### ISSUE THREAD

**Issue by jontyrudman** [stacksmashing/airtag-glitcher#4]
Apologies if this is the wrong place. I've put this here as there's no repo for the pico debug'n'dump hardware - I'm using this code with the DnD to glitch an nRF52832.

The glitch pin hasn’t been shorting to ground. I only read 2.6V on GPIO19/GlitchEn (gpio pin to the mosfet gate) and 1.3V on the gate itself after the resistor. Is this expected? I want to work out whether I’ve blown the mosfet at some point.

All I end up seeing at the time of the glitch on the oscilloscope is a small pulse at the start and end of where the short should occur, but no real change in voltage.

**Comment by nezza** [comment]
Hello Jonathan,

I'll try to reproduce on a board here!

Thanks,
Thomas

**Comment by nezza** [comment]
Ok, short update:

It looks like on some boards the pull-down resistor towards the glitch pin is 100 Ohm instead of 10k Ohm - not sure if mistake in manufacturing data or during manufacturing. Replacing that resistor with a 10k one fixes the issue. Seeing how I can send everyone a replacement resistor :)

**Comment by nezza** [comment]
Ok, quick update: Removing the resistor marked below fixes the issue (The Pi defaults to pulldowns, so that resistor was kind of redundant anyway :) )
![pdnd](https://user-images.githubusercontent.com/208596/145266295-41ae9b16-cdf9-4528-90d9-51add61cfdcf.jpeg)

**Comment by jontyrudman** [comment]
Thanks for looking into it, I'll try removing that resistor soon and update!

**Comment by lukaskuzmiak** [comment]
were both of them supposed to be 10k? I finally managed to steal some time to play with this, so I was going to fix this first.

**Comment by nezza** [comment]
Only the marked one was supposed to be 10k, but as said just removing it works fine!
